#!/usr/bin/env bash
#
# update-download-page.sh — point the web app's /download page at the current Mac release.
#
# Writes public/desktop/latest-mac.json in the WEB repo (Git-Dann/docs-by-gitwork) from the
# artifacts in dist/ + the published GitHub release, and opens a PR (merge → Vercel redeploys →
# foundry.gitwork.co.uk/download shows the new build). Called automatically by publish-update.sh
# and by the release CI; safe to run by hand too.
#
# Requires `gh` authenticated with WRITE access to the web repo. No local clone — uses the
# GitHub Contents API.
#
# Env:
#   WEB_REPO     web repo            (default Git-Dann/docs-by-gitwork)
#   MAC_REPO     this repo           (default Git-Dann/foundry-mac)
#   RELEASE_DATE YYYY-MM-DD          (default: today, UTC)
#   NOTES        JSON array string   (default: a single generated note)
#   DIRECT=1     commit to main directly instead of opening a PR (auto-deploys; no review)
#   DRY_RUN=1    print what would happen; make no remote changes
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="$ROOT/dist"
WEB_REPO="${WEB_REPO:-Git-Dann/docs-by-gitwork}"
MAC_REPO="${MAC_REPO:-Git-Dann/foundry-mac}"
FILE_PATH="public/desktop/latest-mac.json"

VERSION="$(grep -m1 'MARKETING_VERSION' "$ROOT/project.yml" | sed -E 's/.*: *"?([0-9A-Za-z.\-]+)"?.*/\1/')"
BUILD="$(grep -m1 'CURRENT_PROJECT_VERSION' "$ROOT/project.yml" | sed -E 's/.*: *"?([0-9]+)"?.*/\1/')"
TAG="mac-v${VERSION}"

DMG="$(ls -t "$DIST"/*.dmg 2>/dev/null | head -1 || true)"
[ -n "${DMG:-}" ] || { echo "✗ No DMG in $DIST — run build-release.sh + make-dmg.sh + checksum.sh first."; exit 1; }
DMG_NAME="$(basename "$DMG")"
SHA="$(cut -d' ' -f1 "$DMG.sha256" 2>/dev/null || shasum -a 256 "$DMG" | cut -d' ' -f1)"
DMG_URL="https://github.com/${MAC_REPO}/releases/download/${TAG}/${DMG_NAME}"
APPCAST_URL="https://github.com/${MAC_REPO}/releases/latest/download/appcast.xml"
NOTARIZED=true; [[ "$DMG_NAME" == *unsigned-internal* ]] && NOTARIZED=false
RELEASE_DATE="${RELEASE_DATE:-$(date -u +%Y-%m-%d)}"
NOTES="${NOTES:-[\"Foundry for Mac ${VERSION}.\"]}"

JSON=$(cat <<JSON
{
  "version": "${VERSION}",
  "build": "${BUILD}",
  "platform": "macos",
  "arch": "universal",
  "minimumMacOS": "26.0",
  "dmgUrl": "${DMG_URL}",
  "sha256": "${SHA}",
  "releaseDate": "${RELEASE_DATE}",
  "notarized": ${NOTARIZED},
  "sparkleAppcastUrl": "${APPCAST_URL}",
  "notes": ${NOTES}
}
JSON
)

echo "▸ ${WEB_REPO}:${FILE_PATH}"
echo "$JSON"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  echo "▸ DRY_RUN — no remote changes made."
  exit 0
fi

command -v gh >/dev/null || { echo "✗ gh not installed."; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "✗ gh not authenticated (needs write access to ${WEB_REPO})."; exit 1; }

B64="$(printf '%s' "$JSON" | base64 | tr -d '\n')"
COMMIT_MSG="chore(download): Foundry for Mac ${VERSION} (build ${BUILD})"

put_file() { # $1 = branch
  local branch="$1"
  local file_sha
  file_sha="$(gh api "repos/${WEB_REPO}/contents/${FILE_PATH}?ref=${branch}" --jq .sha 2>/dev/null || true)"
  gh api "repos/${WEB_REPO}/contents/${FILE_PATH}" -X PUT \
    -f message="${COMMIT_MSG}" -f content="${B64}" -f branch="${branch}" \
    ${file_sha:+-f sha="${file_sha}"} >/dev/null
}

if [[ "${DIRECT:-0}" == "1" ]]; then
  echo "▸ Committing directly to main (auto-deploys)…"
  put_file "main"
  echo "✓ /download will update on the next Vercel deploy."
else
  BRANCH="mac-release/${TAG}"
  MAIN_SHA="$(gh api "repos/${WEB_REPO}/git/ref/heads/main" --jq .object.sha)"
  gh api "repos/${WEB_REPO}/git/refs" -f ref="refs/heads/${BRANCH}" -f sha="${MAIN_SHA}" >/dev/null 2>&1 || true
  put_file "${BRANCH}"
  if gh pr view "${BRANCH}" --repo "${WEB_REPO}" >/dev/null 2>&1; then
    echo "✓ Updated existing PR for ${BRANCH}"
  else
    gh pr create --repo "${WEB_REPO}" --base main --head "${BRANCH}" \
      --title "chore(download): Foundry for Mac ${VERSION}" \
      --body "Auto-generated by the Mac release flow. Points /download at \`${DMG_NAME}\` (sha256 \`${SHA}\`). Merge to publish to foundry.gitwork.co.uk/download." \
      | tail -1
  fi
  echo "✓ Merge the PR to publish the new build to /download."
fi
